### ISSUE TITLE
Dependency on libconfig++-dev missing in the README.md

### ISSUE THREAD

**Issue by gaya-** [code-iai/semrec#20]
There isn't a rosdep key for it but adding it to the list in the readme could be useful.

**Comment by gaya-** [comment]
Also, a dependency on libjson0-dev would be nice (sorry for the mixed issue title).
https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1579

**Comment by SuzanaK** [comment]
All in one command:

_sudo apt-get install libncurses5-dev automake autoconf sudo apt-get install libconfig++8-dev libjson0-dev_

**Comment by fairlight1337** [comment]
You left an additional `sudo` after `autoconf`, but thanks a lot. I'll add it to the README.md.

**Comment by SuzanaK** [comment]
Oops...

**Comment by fairlight1337** [comment]
Done in 7244f23ed9090c094306d0dd661fba1ca3d5dde2.
